org: nautech
app: get-task
service: seek-interview

provider:
  name: aws
  ecr:
    images:
      baseimage:
        path: ./
  httpApi:
    cors: true

functions:
  get-task:
    image:
      name: baseimage
      command:
        - get/handler.get
    events:
      - httpApi:
          path: /
          method: get
  post-task:
    image:
      name: baseimage
      command:
        - post/handler.post
    events:
      - httpApi:
          path: /create
          method: post
  put-task:
    image:
      name: baseimage
      command:
        - put/handler.put
    events:
      - httpApi:
          path: /edit/{task_id}
          method: put
  delete-task:
    image:
      name: baseimage
      command:
        - delete/handler.delete
    events:
      - httpApi:
          path: /delete/{task_id}
          method: delete
